### ISSUE TITLE
Hostgator

### ISSUE THREAD

**Issue by wiltonbarros** [QuilhaSoft/JasperPHP#14]
@Rctnet boa tarde!
Este projeto roda na hospedagem compartilhada do hostgator?
Obrigado!

**Comment by Rctnet** [comment]
Boa tarde @wiltonbarros , sim, os Live samples do readme do projeto estão rodando no hostgator

**Comment by wiltonbarros** [comment]
Estou com um projeto parecido rodando no hostgator phpjasper, estou enfrentando um problema e o pessoal da hostgator diz que não tem suporte, pois necessita do jdk, como você faz a conversão do arquivo jasper para o php?
Obrigado!

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by Rctnet** [comment]
O arquivo jasper.jrxml, na verdade é um xml comum, faço o parser dele e vou criando objetos php para gerenciar cada nó do xml, cada nó cria suas instruções para geração do pdf e deposita num array, esse array é processado posteriormente, criando o arquivo pdf em si. não é simples, mas é elegante, e puro PHP.
Uso nos meus sistemas a mais de 3 anos

**Comment by wiltonbarros** [comment]
Qual a diferença do seu projeto para o Phpjasper? Lá tenho que gerar um arquivo .jasper.
Obrigado!

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by Rctnet** [comment]
Eu nunca usei o Phpjasper, mas o basico é que quando você usa o jdk do java quem roda o relatório é a biblioteca original do Jasper, no meu tudo teve que ser arranjado em php para coincidir o máximo com a biblioteca original, alguns componentes ainda não foram portados, como tabela dinâmica, no readme tem uma lista de tudo que é suportado, quanto ao arquivo .jasper, uso só o .jrxml

**Comment by wiltonbarros** [comment]
Obrigado pelo retorno!
Vou implementar em meu projeto.
________________________________
De: Rogerio Muniz <notifications@github.com>
Enviado: quinta-feira, 18 de julho de 2019 17:01
Para: QuilhaSoft/JasperPHP
Cc: wiltonbarros; Mention
Assunto: Re: [QuilhaSoft/JasperPHP] Hostgator (#14)


Eu nunca usei o Phpjasper, mas o basico é que quando você usa o jdk do java quem roda o relatório é a biblioteca original do Jasper, no meu tudo teve que ser arranjado em php para coincidir o máximo com a biblioteca original, alguns componentes ainda não foram portados, como tabela dinâmica, no readme tem uma lista de tudo que é suportado, quanto ao arquivo .jasper, uso só o .jrxml
