### ISSUE TITLE
por que o parametro logoPath não funciona?

### ISSUE THREAD

**Issue by marcelocajaiba** [QuilhaSoft/JasperPHP#15]
Olá amigos estou tentando por a logo nos carnês mas o parâmetro logoPath não funciona, alguém sabe de uma solução para isso? obrigado

**Comment by Rctnet** [comment]
Ola @marcelocajaiba , você quer mudar a logo do banco ou adicionar logo da empresa?
caso seja a do banco, você deve substituir a imagen na pasta do openboleto.

**Comment by marcelocajaiba** [comment]
olá Rogério, obrigado, mas é que eu queria mudar dinâmicamente em outra pasta

**Comment by Rctnet** [comment]
Bom dia, no arquivo jrxml mode o nome da variável na tag 
<imageExpression><![CDATA[$F{logo_banco}]]></imageExpression>,
Mude para
<imageExpression><![CDATA[$F{logo_banco2}]]></imageExpression>
a variável logo_banco é manipulada em tempo real pela biblioteca openboleto, por isso você não consegue alterar a propriedade... logoPath
mas se o nome da variável for outro o openboleto não tocara nela.

na linha 129 do itaujasper.php
acrescente 
$this-data['logo_banco2'] = 'url do arquivo';
isso deve resolver.
que a força esteja com você.

**Comment by marcelocajaiba** [comment]
Muito Obrigado Rogério
