### ISSUE TITLE
localhost relatório não carrega

### ISSUE THREAD

**Issue by Danillosdd** [QuilhaSoft/JasperPHP#16]
Boa Tarde, 

Acho que não entendi a documentação.

Mais eu baixei a pasta descompactei, edite o dev.ini criei um arquivo.php com o contéudo da documentação, criei um template.jrxml somente com texto(sem acesso no banco de dados) apenas pra teste mesmo; coloquei o e chamei no browser o arquivo.php, mais acusa:

`localhost não consegue atender a esta solicitação no momento.`

Desde já agradeço

**Comment by Rctnet** [comment]
Boa tarde, essa mensagem é de erro 500, pode ser que a versão do php esteja errada, recomendo 7.2

**Comment by Danillosdd** [comment]
Estou usando a PHP 7.2.24-0ubuntu0.18.04.1 (cli) (built: Oct 28 2019 12:07:07) ( NTS )

**Comment by Rctnet** [comment]
Bom dia, a versão do PHP não deve ser problema... tentou rodar o exemplo da pasta samples?

**Comment by Rctnet** [comment]
Bom dia @Danillosdd , resolvido problema para carregar relatório fora da pasta default, atualize sua biblioteca para aplicar a correção.
