### ISSUE TITLE
Error on band Title

### ISSUE THREAD

**Issue by ctodobom** [QuilhaSoft/JasperPHP#19]
When using the band Title there is an unknown variable being referenced: `$rowIndex`.

I do not know what is expected, I changed my local code to point to the first record if datasource is an array:

```diff
diff --git a/src/Title.php b/src/Title.php
index 121b256..c94f406 100644
--- a/src/Title.php
+++ b/src/Title.php
@@ -20,8 +20,7 @@ class Title extends Element {
         $recordObject = array_key_exists('recordObj', $arrayVariable) ? $arrayVariable['recordObj']['initialValue'] : "stdClass";
         // echo  $recordObject;
         //var_dump($obj);
-        $row = ( is_array($dbData) ) ? (array_key_exists($rowIndex, $dbData)) ? $dbData[$rowIndex] : null : $obj->rowData;
-        //$obj->rowData = $row;
+        $row = ( is_array($dbData) ) ? (array_key_exists(0, $dbData)) ? $dbData[0] : null : $obj->rowData;
         if ($row) {
             switch ($row) {
                 case (is_object($row)):
```

**Comment by Rctnet** [comment]
You are correct in change your local code to point to first record, i create a array as datasource feature in Detail.php and copy/paste to title.php, but i missing $rowIndex variable treatement, if you make it as  in detail.php, set $rowIndex to 0 before this line, and make a PR

**Comment by ctodobom** [comment]
Just checked out your fix and sent a PR fixing a small typo on it.

thank you.
