### ISSUE TITLE
Can't see items on Column footer band and page footer band

### ISSUE THREAD

**Issue by n05f3r47u** [QuilhaSoft/JasperPHP#42]
After try this I can see items and fields on page header, column header and detail but I can't see items on Column footer band or page footer band
![img_data](https://user-images.githubusercontent.com/963187/88750770-d66cd400-d11b-11ea-802a-f82d5f8ff9a8.png)

PDF generated by app
![img_no_data](https://user-images.githubusercontent.com/963187/88750812-ea183a80-d11b-11ea-95c7-fcd69b2f1522.png)

**Comment by onoboaits** [comment]
Estimado, mi nombre es Omar Noboa, veo que hablas español y haz podido utilizar la clase podrías darme tu correo para hacerte unas consultas, mi correo es onoboaits@gmail.com

**Comment by Rctnet** [comment]
Si, pero no mucho, rsrsr soy brasileño, mas puedes mandar que voy a hacer todo lo posible para ayudarte.
Quanto a este tu problema, tente carregar estes campos en variables, talves funcione de imediato, toda via empessarei una busca para levar os dados del ultimo registro para las bands

**Comment by Rctnet** [comment]
mi correo es rogerio@quilhasoft.com.br

**Comment by n05f3r47u** [comment]
Hola, Cargar los campos en variables funcionó perfecto para los strings. Gracias...! Obrigado..!
El problema ahora es que las fechas no se dejan ver. Aparece un número que no corresponde a la fecha

**Comment by Rctnet** [comment]
Hola, yo add un update para carga en direto de los campos, update su code
segue https://github.com/QuilhaSoft/JasperPHP/commit/bb4b1e3c3a1567b9de8b06c8d1b2ee790ef5f67e

**Comment by n05f3r47u** [comment]
Obrigado , meu amigo. Agora funciona perfeito
