### ISSUE TITLE
$P!{name}  Parameters

### ISSUE THREAD

**Issue by gamadoleo** [QuilhaSoft/JasperPHP#46]
how to work with this type of parameter, used for example to pass sql statements, I know it may be a failure for sql injector but it will not be used for parameter edited by the user and in jasperReporta it works normally. I wanted to know how to adopt in your api.

select * from pessoa where ($P!{p_where})

??

**Comment by gamadoleo** [comment]
Can anyone pass these parameters?

**Comment by Rctnet** [comment]
Hi, 
this is a complex sql, i use it in my systems
SELECT p.proprietarios_codigo, 
p.proprietarios_nome,
cc.cc_terceiros_codigo,
cc.bancos_codigo,
cc.cc_terceiros_agencia,
cc.cc_terceiros_conta,
cc.cc_terceiros_tipo,
cc.cc_terceiros_titular,
cc.cc_terceiros_cnpjcpf,
l.locacoes_codigo,
b.bancos_nome
FROM locacoes l
 JOIN imoveis_proprietarios ip ON ip.imoveis_codigo = l.imoveis_codigo
 JOIN cc_terceiros cc ON cc.cc_terceiros_codigo = ip.cc_terceiros_codigo
 JOIN proprietarios p ON p.proprietarios_codigo = ip.proprietarios_codigo 
 JOIN bancos b ON b.bancos_codigo = cc.bancos_codigo
 JOIN eventos_locacao evl ON l.locacoes_codigo = evl.locacoes_codigo
 WHERE evl.proprietario_dta_venc >=  "$P{dta_repasse_inicial}"
  AND evl.proprietario_dta_venc <= "$P{dta_repasse_final}" 
 AND evl.situacao = "NOR" 
  $P{rd_filtrar_pagos}  
  $P{rd_filtrar_prop_imov} 
  $P{rd_filtrar_repassados} 
  GROUP BY p.proprietarios_codigo,cc.cc_terceiros_conta
  ORDER BY p.proprietarios_nome ASC

**Comment by gamadoleo** [comment]
I understand, in making filters based on individual parameters, but that makes the sql assembly much more complex... something that in the application there are many filters and makes them dynamic, so when passing the formulated parameter already as a kind of p_where, it makes it easier the process a lot, and as I said that way jasperreport native jasper api supports... and it makes it much easier to use this type of parameter, with that I pass a completely customized p_where.

**Comment by Rctnet** [comment]
try this ($P{p_where}) without "!"
select * from person where ($P{p_where})
and pass a sql in the parameter
p_where = city_id=10 and neighborhood_id=25

**Comment by gamadoleo** [comment]
Without ! seems to solve yes... because I did a debug printing the generated sql and now yes it is generating correctly... but I have other problems in the report anything I open another post. Here's just one suggestion that I inform you is the possibility of changing the patch directory of ini config files for database connection because in my case, I already have this file pattern because I also use PDO so I wanted to use the same files...
One question what makes a report slow? because I'm testing your library I already use the report with jar JasperStart but your generated even slower... I didn't understand.

**Comment by Rctnet** [comment]
About PDO, i use one solution, runs perfect for me, you can change on line https://github.com/QuilhaSoft/JasperPHP/blob/ee16f92927503282c67683f8d4b8387878aea344/src/Report.php#L7
and implement a copy of Transaction Class, but taking connection parameters in your config file.
About slow reports, i think that much objects can make report slower, i have in my systems reports what generate mor then 60 pages in less of 6 seconds, containing 3 level sub reports with querys, passing parameters end receiving totalizers.

**Comment by gamadoleo** [comment]
JasperPHP\ado\TTransaction::open("dev");

when I refer to changing the patch, I refer to the possibility, for example, of changing the directory where the dev.ini file is, or even some parameter that says that a complete patch of the file is being passed, because as I said, I already have files in another folder ini config files and didn't want to be duplicating the config files

**Comment by Rctnet** [comment]
Add the solution
https://github.com/QuilhaSoft/JasperPHP/blob/c1a338ddf63710d26fdda61ac2176e4ce33890aa/src/ado/TConnection.php#L30
pass full path of file including extension

**Comment by gamadoleo** [comment]
yes..
