### ISSUE TITLE
Conditional print how to use?

### ISSUE THREAD

**Issue by gamadoleo** [QuilhaSoft/JasperPHP#47]
conditional print how to use?
I have reports that I basically use two functions for.
New Boolean and the AND() and OR() functions all native to jasper report, I realize that JasperPHP doesn't work I would like to know what is the recommendation to work with conditional print and how I can adapt my example:
printWhenExpression:

AND(new Boolean($F{invoice_bar_code} != null), new Boolean($F{invoice_payment_form_id} != 4) )

**Comment by Rctnet** [comment]
Use a PHP "if" default condition sintaxe. in future can be implement to make compatibility to jasper native functionality.

**Comment by gamadoleo** [comment]
I understand the point is that since I use jasper itself to test and see the behavior, I thought it would be possible to maintain compatibility between both

**Comment by gamadoleo** [comment]
Another problem I've noticed is related to the use of the jasper concatenate

see the example:
$F{customer_name}+
" CPF/CNPJ: "+$F{cliente_cpf_cnpj}+"\n"+
$F{client_address_cobranca}

JasperPHP does not deal with this issue and the "+" sign is displayed on screen, exactly the same thing, for example, if I mount a file patch by concatenating the address with a database variable

**Comment by Rctnet** [comment]
see this sample
https://github.com/QuilhaSoft/JasperPHP/blob/c1a338ddf63710d26fdda61ac2176e4ce33890aa/samples/bol01Files/boletoA4.jrxml#L753
