### ISSUE TITLE
Suport add element frame?

### ISSUE THREAD

**Issue by gamadoleo** [QuilhaSoft/JasperPHP#48]
There is the possibility of adding support to the frame element, as I use it to group elements within the report and allowing, for example, to apply a specific placement in the frame and it auto-adjusts to the content that contains them

**Comment by gamadoleo** [comment]
Apparently Frame has similar behavior to Band, so I created class Frame exactly like class Band and it's working, I ask that if possible include this class Frame based on class Band

**Comment by Rctnet** [comment]
I hope you include a Pull Request with those updates, this is a way to make this project big, more contributors give be more visibility to project

**Comment by gamadoleo** [comment]
received the pull request?

**Comment by Rctnet** [comment]
no
