### ISSUE TITLE
Does not respect the positioning

### ISSUE THREAD

**Issue by gamadoleo** [QuilhaSoft/JasperPHP#49]
Look guys, I'm facing a problem of misconfiguring the positioning of the text fields when generating in jasperphp I would like to know if there is any detail to be done to avoid this, the report generated in jasper studio and jasperphp is attached.

![jasper report](https://user-images.githubusercontent.com/23720707/121900179-867b0980-ccfb-11eb-8b11-27485571a0ac.png)
![jasperphp](https://user-images.githubusercontent.com/23720707/121900183-87ac3680-ccfb-11eb-8128-d1e66b5eeba7.png)

**Comment by gamadoleo** [comment]
![debugando](https://user-images.githubusercontent.com/23720707/121907873-dad5b780-cd02-11eb-9aa6-7270bf7c228b.png)

See, I did a debug of the positions displaying the x and y coordinates and amazingly it seems to be displaying both at the same y position, but I don't respect that

**Comment by Rctnet** [comment]
Yes, i have this bug, think is the problem with FPDF, but if you fix e one pixel of space between objects, solve this problem

**Comment by gamadoleo** [comment]
thank you, I did this fine-tuning between the text fields and unchecked the strech overflow, a single item had a problem, I deleted it and created it again and now everything is aligned...
![strech](https://user-images.githubusercontent.com/23720707/121913645-f2636f00-cd07-11eb-94e7-ec38bc832026.png)
