### ISSUE TITLE
Need full document

### ISSUE THREAD

**Issue by bdlogicalerror** [QuilhaSoft/JasperPHP#5]
i want to integrate  this library in my project.but i can't,can u please help me

**Comment by Rctnet** [comment]
What you need, maybe we can help you.

**Comment by bdlogicalerror** [comment]
i can't use it on project it's give me 500 error

**Comment by Rctnet** [comment]
you use composer instalation or dowload?

**Comment by bdlogicalerror** [comment]
i was use download

**Comment by Rctnet** [comment]
a package "tecnickcom/tcpdf":"6.2.*" is necessary 
in TJasper.class.php file, on line 77 i require it

**Comment by bdlogicalerror** [comment]
may be this is the mistake.can u please share the db.which are related with your sample

**Comment by Rctnet** [comment]
the db conection is only necessary for test instalation, the query into xmlr is not select any table ex: SELECT now(), '$P{locacoes_dia_repasse}' as  locacoes_dia_repasse

**Comment by Rctnet** [comment]
only for other samples, in this case i wich to create a db sample and samples reports

**Comment by bdlogicalerror** [comment]
thanks for help me. IT's working..
