### ISSUE TITLE
HEADER COLUMN REPEAT?

### ISSUE THREAD

**Issue by gamadoleo** [QuilhaSoft/JasperPHP#67]
Hello, this project has gotten better and better, and it will really make reporting a lot easier, especially for those who don't want to rely on java generators.

And I hope it gets better and better!
See only COLUMN HEADER is supported in JASPERPHP generator, but there is a behavior that we could improve, the COLUMN HEADER in its default behavior is repeated on all pages (in JASPER STUDIO), but in JASPERPHP this does not happen, how could we implement this behavior? wouldn't it be possible to make HEADER COLUMN REPEAT?

**Comment by Rctnet** [comment]
it is possible, see this line
https://github.com/QuilhaSoft/JasperPHP/blob/0d75a2ded5d1a3869aaae4e6b7892ae0f23da444/src/PdfProcessor.php#L82
but must have a option to print only once

**Comment by gamadoleo** [comment]
Check it out: I believe that the default behavior of COLUMN HEADER should be repeating, because in order not to repeat there is already another band (TITLE), this is the default behavior of JASPER, now it is clear for groups there really is a possibility to repeat or not every new page, and as I argue, we should always have an idea to maintain a maximum compatibility with default behavior

**Comment by gamadoleo** [comment]
Okay, I'll adjust to keep the pattern without repeating in whoever wants to activate the repeat ok? I'm going to send a pool request.
