### ISSUE TITLE
Rectangle does not put the border?

### ISSUE THREAD

**Issue by gamadoleo** [QuilhaSoft/JasperPHP#70]
I have been using the rectangle component, but it does not respect the application of the border, how can we check to solve this? or am i doing something wrong?

**Comment by Rctnet** [comment]
https://github.com/QuilhaSoft/JasperPHP/blob/2a29df7792a83800a58a374d04df0ea87fc54747/src/PdfProcessor.php#L196

**Comment by gamadoleo** [comment]
I know this is where he was created. One question, does the rectangle edge work for you?

**Comment by gamadoleo** [comment]
when debugging the border style, see that it passes the parameters, I really don't understand why for me the rectangle border doesn't apply...

```
$border_style

{"width":{"0":"0.5"},"color":{"r":0,"g":0,"b":0},"cap":"square","join":"miter","dash":""}
```

**Comment by gamadoleo** [comment]
look, when analyzing, I can put the border, but the fill doesn't work, so we can add it in two steps and we get the result of the border and also the fill.

`    public function RoundedRect($arraydata) {
        if ($arraydata['mode'] == 'Transparent')
            $style = '';
        else
            $style = 'FD';
        //
        //        
		JasperPHP\Instructions::$objOutPut->RoundedRect($arraydata["x"] + JasperPHP\Instructions::$arrayPageSetting["leftMargin"], $arraydata["y"] + JasperPHP\Instructions::$y_axis, $arraydata["width"], $arraydata["height"], $arraydata["radius"], '1111', $style, $arraydata['border'], $arraydata['fillcolor']);
		
		JasperPHP\Instructions::$objOutPut->SetLineStyle($arraydata['border']);
		JasperPHP\Instructions::$objOutPut->RoundedRect($arraydata["x"] + JasperPHP\Instructions::$arrayPageSetting["leftMargin"], $arraydata["y"] + JasperPHP\Instructions::$y_axis, $arraydata["width"], $arraydata["height"], $arraydata["radius"], '1111',$arraydata['border']);		
		JasperPHP\Instructions::$objOutPut->SetLineStyle(array());
        
    }`

we could improve, but I believe it is enough, what is your assessment?

**Comment by Rctnet** [comment]
Perfect, PR now, rsrs
