### ISSUE TITLE
How can i use json data and jasper variable also not work

### ISSUE THREAD

**Issue by bdlogicalerror** [QuilhaSoft/JasperPHP#8]
hey there, here mysql database working fine without any problem but how can i use JSON data and here JASPER Variable like report count does not work

**Comment by Rctnet** [comment]
hi, those variables realy not work, show me repor_count variable functionality and i implement it.

**Comment by Rctnet** [comment]
about json data,see sample in https://github.com/QuilhaSoft/JasperPHP-OpenBoleto/blob/master/itauJasperA4.php

**Comment by bdlogicalerror** [comment]
report count variable means in loop index like a table serial
