### ISSUE TITLE
Subreports

### ISSUE THREAD

**Issue by onoboaits** [QuilhaSoft/JasperPHP#86]
Estimados todos, tengo un problema al querer exportar un reporte que contiene Sub-reportes, en el Jasper Report 6.0 no me presenta ningún problema, se muestra correctamente, pero al momento de ejecutarlo en la aplicación, me aparece el error que indica que no se encuentra el archivo, he intentado poniendo solo el nombre del reporte (que esta en el mismo directorio que el principal) y poniendo la ruta completa del archivo, pero de ninguna de las dos maneras muestra el reporte.

Adjunto el mensaje de error: 

Fatal error: Uncaught JasperPHP\Exception: File http://localhost:8089/hrmedic/jasperphp/report/rpthisrec.jasper not found!! in C:\xampp\htdocs\hrmedic\JasperPHP\src\Report.php:47 Stack trace: #0 C:\xampp\htdocs\hrmedic\JasperPHP\src\Subreport.php(40): JasperPHP\Report->__construct('http://localhos...', Array) #1 C:\xampp\htdocs\hrmedic\JasperPHP\src\Band.php(26): JasperPHP\Subreport->generate(Object(JasperPHP\Report)) #2 C:\xampp\htdocs\hrmedic\JasperPHP\src\Element.php(174): JasperPHP\Band->generate(Object(JasperPHP\Report)) #3 C:\xampp\htdocs\hrmedic\JasperPHP\src\GroupHeader.php(40): JasperPHP\Element->generate(Array) #4 C:\xampp\htdocs\hrmedic\JasperPHP\src\Element.php(174): JasperPHP\GroupHeader->generate(Object(JasperPHP\Report)) #5 C:\xampp\htdocs\hrmedic\JasperPHP\src\GroupHeader.php(40): JasperPHP\Element->generate(Array) #6 C:\xampp\htdocs\hrmedic\JasperPHP\src\Detail.php(44): JasperPHP\GroupHeader->generate(Object(JasperPHP\Report)) #7 C:\xampp\htdocs\hrmedic\JasperPHP\src\Element.php(174): JasperPHP\Detail->ge in C:\xampp\htdocs\hrmedic\JasperPHP\src\Report.php on line 47

![image](https://user-images.githubusercontent.com/43496724/131710395-9e13fd50-de57-4e44-b185-9142683fff35.png)

En Jasper Report 6.0 Preview
![image](https://user-images.githubusercontent.com/43496724/131711053-aba75bfa-751d-4cd6-889e-610f598ff7bf.png)

**Comment by Rctnet** [comment]
Ola, neste link muestra el código donde carrega el ficheiro
https://github.com/QuilhaSoft/JasperPHP/blob/15d8df1f7c6b094fd00a663466acaa841e1a16a5/src/Report.php#L42

**Comment by onoboaits** [comment]
Resuelto, lo tenia mal direccionado. gracias
